[package]
name          = "uaparser"
version       = "0.3.2"
description   = "A Rust implementation of the UA Parser"
license       = "MIT"
authors       = ["David Lewis <david@weassemble.com>"]
edition       = "2018"

homepage      = "https://github.com/davidarmstronglewis/uap-rs"
repository    = "https://github.com/davidarmstronglewis/uap-rs"
documentation = "https://docs.rs/uap-rs/"
readme        = "README.md"

keywords      = ["user", "agent", "parser", "uap", "uaparser"]

[dependencies]
serde = "1.0.99"
serde_yaml = "0.8.9"
serde_derive = "1.0.99"
derive_more = "0.99.2"
fancy-regex = "0.3.1"
